#!/bin/bash
### BEGIN INIT INFO
# Provides:          pyKMS
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: pyKMS
# Description:       pyKMS
### END INIT INFO
start() {
 python -u /usr/local/pykms/server.py 1>> /usr/local/pykms/pykms.log &2>> /usr/local/pykms/pykms_err.log
}
stop() {
  killall python
}
case $1 in
start)
  start || exit 1
  ;;
stop)
  stop || exit 1
  ;;
*)
  echo "Usage: $0 start|stop" 1>&2
  exit 1
esac
